# .cnb.yml
$:
  vscode:
    - docker:
        image: docker.cnb.cool/magiccode1412/universal/node_20_dev:latest
      services:
        - vscode
        - docker
      stages:
        - name: install dependence
          script: bash scripts/dev.sh

main:
  web_trigger_main:
    - services:
        - docker
      imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      stages:
        - name: docker build
          script: bash scripts/docker.sh main

  push:
    - imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      stages:
        - name: sync_to_github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/${GITHUB_USERNAME}/${CNB_REPO_NAME_LOWERCASE}.git
            auth_type: https
            username: "${GITHUB_USERNAME}"
            password: "${GITHUB_ACCESS_TOKEN}"
            force: true
dev:
  web_trigger_dev:
    - services:
        - docker
      imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      stages:
        - name: docker build
          script: bash scripts/docker.sh dev